import random
from tkinter import *

window = Tk()
questionpicture=PhotoImage(file="question.png")
questionpicture1=questionpicture.subsample(2,2)
def choice1():
    choice_win = Toplevel()
    choice_win.title("choose")
    mode_var = IntVar(value=1)
    yes_button = Radiobutton(choice_win, text="Yes", variable=mode_var, value=1)
    no_button = Radiobutton(choice_win, text="No", variable=mode_var, value=2)
    yes_button.pack()
    no_button.pack()
    def yesorno():
        select = mode_var.get()  
        choice_win.destroy()      
        click1(select)           
    buttonyon = Button(choice_win, text="confirm", command=yesorno)
    buttonyon.pack()
def click1(mode):
    game1 = Toplevel()
    game1.title("21 games")
    back = PhotoImage(file="normal.png")
    background=back.subsample(2,2)
    totalnumber=21
    canvas1 = Canvas(game1, width=background.width(), height=background.height(), highlightthickness=0)
    canvas1.pack()
    canvas1.background = background
    canvas1.create_image(0, 0, anchor="nw", image=background)
    text_=canvas1.create_text(480, 65, text=f"Total number:{totalnumber}",font=("Ariel",40))
    listplayer=[]
    listcomputer=[]
    text1=canvas1.create_text(480,110,text=f"you: {listplayer}", font=("Ariel",20))
    text2=canvas1.create_text(480,140,text=f"computer: {listcomputer}", font=("Ariel",20))
    if mode==2:
        import random
        a=random.randint(1,3)
        totalnumber-=a
        listcomputer.append(a)
        canvas1.itemconfig(text2,text=f"computer: {listcomputer}")
        canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
    def gameover(mode,game1):
        over=Toplevel()
        over.title("game over")
        labelover= Label(over, text="You lose!")
        def play_again():
            over.destroy()
            game1.destroy()
            choice1()
              
        def back_to_menu():
            over.destroy()
            game1.destroy()           
        labelover.pack()
        buttonplayagain= Button(over, text="Play Again", command=play_again)
        buttonplayagain.pack()
        buttonbacktomenu= Button(over, text="Back to Menu", command=back_to_menu)
        buttonbacktomenu.pack()
    def gamewin(mode,game1):
        win=Toplevel()
        win.title("you win")
        labelwin= Label(win, text="You win!")
        def play_again():
            win.destroy()
            game1.destroy()
            choice1()
            click1(mode)              
        def back_to_menu():
            win.destroy()
            game1.destroy()           
        labelwin.pack()
        buttonplayagain= Button(win, text="Play Again", command=play_again)
        buttonplayagain.pack()
        buttonbacktomenu= Button(win, text="Back to Menu", command=back_to_menu)
        buttonbacktomenu.pack()               
    def click11():
        game11=Toplevel()
        game11.title("rules")
        bkk=PhotoImage(file="1.1.png")
        bk2 = bkk.subsample(2,2)
        label11= Label(game11, image=bk2)
        label11.pack()
        game11.mainloop()
        game11=Toplevel()
        game11.title("rules")
        bk=PhotoImage(file="1.1.png")
        bk1 = bk.subsample(2,2)
        label11= Label(game11, image=bk1)
        label11.pack()
    def add1():
        if mode==1:
            nonlocal totalnumber
            totalnumber-=1    
            listplayer.append(1)
            canvas1.itemconfig(text1,text=f"you: {listplayer}")
            canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
            if totalnumber<=0:
                gameover(mode,game1)
                return
            else:
                totalnumber-=3
                listcomputer.append(3)
                canvas1.itemconfig(text2,text=f"computer: {listcomputer}")
                canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
                
        else:
            
            totalnumber-=1    
            listplayer.append(1)
            canvas1.itemconfig(text1,text=f"you: {listplayer}")
            canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
            if totalnumber<=0:
                gameover(mode,game1)
                return  
            else:
                import random
                a=random.randint(1,3)
                totalnumber-=a
                listcomputer.append(a)
                canvas1.itemconfig(text2,text=f"computer: {listcomputer}")
                canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
                if totalnumber<=0:
                    gamewin(mode,game1)
                    return              
    def add2():
        if mode==1:
            nonlocal totalnumber
            totalnumber-=2    
            listplayer.append(2)
            canvas1.itemconfig(text1,text=f"you: {listplayer}")
            canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
            if totalnumber<=0:
                gameover(mode,game1)
                return
            else:
                totalnumber-=2
                listcomputer.append(2)
                canvas1.itemconfig(text2,text=f"computer: {listcomputer}")
                canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
                if totalnumber<=0:
                    gamewin(mode,game1)
                    return
        else:
            
            totalnumber-=2    
            listplayer.append(2)
            canvas1.itemconfig(text1,text=f"you: {listplayer}")
            canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
            if totalnumber<=0:
                gameover(mode,game1)
                return
            else:
                import random
                a=random.randint(1,3)
                totalnumber-=a
                listcomputer.append(a)
                canvas1.itemconfig(text2,text=f"computer: {listcomputer}")
                canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
                if totalnumber<=0:
                    gamewin(mode,game1)
                    return
    def add3():
        if mode==1:
            nonlocal totalnumber
            totalnumber-=3    
            listplayer.append(3)
            canvas1.itemconfig(text1,text=f"you: {listplayer}")
            canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
            if totalnumber<=0:
                gameover(mode,game1)
                return
            else:
                totalnumber-=1
                listcomputer.append(1)
                canvas1.itemconfig(text2,text=f"computer: {listcomputer}")
                canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
                if totalnumber<=0:
                    gamewin(mode,game1)
                    return
        else:
            
            totalnumber-=3    
            listplayer.append(3)
            canvas1.itemconfig(text1,text=f"you: {listplayer}")
            canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
            if totalnumber<=0:
                gameover(mode,game1)
                return
                gameover(mode,game1)
            else:
                import random
                a=random.randint(1,3)
                totalnumber-=a
                listcomputer.append(a)
                canvas1.itemconfig(text2,text=f"computer: {listcomputer}")
                canvas1.itemconfig(text_,text=f"Total number:{totalnumber}")
                if totalnumber<=0:
                    gamewin(mode,game1)
                    return
    buttona1 = Button(game1,borderwidth=0, highlightthickness=0,image=questionpicture1)
    buttona1.place(x=10,y=100,width=50,height=50)
    buttona1.config(command=click11)
    buttonone = Button(game1, text="1",bg="#41AB4C",font=("Ariel",40))
    buttonone.place(x=180,y=250,width=150,height=150)
    buttontwo = Button(game1,text="2",bg="#41AB4C", font=("Ariel",40))
    buttontwo.place(x=406,y=250,width=150,height=150)
    buttonthree = Button(game1,text="3",bg="#41AB4C", font=("Ariel",40))
    buttonthree.place(x=632,y=250,width=150,height=150)
    buttonone.config(command=add1)
    buttontwo.config(command=add2)
    buttonthree.config(command=add3)
def click2():
    game2 = Toplevel()
    game2.title("Tic Tac Toe")
    back = PhotoImage(file="normal.png")
    background=back.subsample(2,2)
    label2 = Label(game2, image=background)
    label2.pack()
    def click22():
        game22=Toplevel()
        game22.title("rules")
        bkk=PhotoImage(file="2.1.png")
        bk2 = bkk.subsample(2,2)
        label22= Label(game22, image=bk2)
        label22.pack()
        game22.mainloop()
    buttona2 = Button(game2,borderwidth=0, highlightthickness=0,image=questionpicture1)
    buttona2.place(x=10,y=100,width=50,height=50)
    buttona2.config(command=click22)

    game2.mainloop()
def click3():
    game3 = Toplevel()
    game3.title("Find planes' head")
    back = PhotoImage(file="normal.png")
    background=back.subsample(2,2)
    label3 = Label(game3, image=background)
    label3.image = background
    label3.pack()
    def click33():
        game33 = Toplevel()
        game33.title("rules")
        game333 = PhotoImage(file="3.1.png")
        bk3 = game333.subsample(2,2)
        label33 = Label(game33, image=bk3)
        label33.image = bk3  
        label33.pack()
    border = Frame(game3, bg="black")
    border.place(x=230, y=50, width=473, height=473)
    buttons1 = Button(border, borderwidth=0, bg="white")
    buttons1.place(x=2, y=2, width=46, height=46)
    buttons2 = Button(border, borderwidth=0, bg="white")
    buttons2.place(x=49, y=2, width=46, height=46)
    buttons3 = Button(border, borderwidth=0, bg="white")
    buttons3.place(x=96, y=2, width=46, height=46)
    buttons4 = Button(border, borderwidth=0, bg="white")
    buttons4.place(x=143, y=2, width=46, height=46)
    buttons5 = Button(border, borderwidth=0, bg="white")
    buttons5.place(x=190, y=2, width=46, height=46)
    buttons6 = Button(border, borderwidth=0, bg="white")
    buttons6.place(x=237, y=2, width=46, height=46)
    buttons7 = Button(border, borderwidth=0, bg="white")
    buttons7.place(x=284, y=2, width=46, height=46)
    buttons8 = Button(border, borderwidth=0, bg="white")
    buttons8.place(x=331, y=2, width=46, height=46)
    buttons9 = Button(border, borderwidth=0, bg="white")
    buttons9.place(x=378, y=2, width=46, height=46)
    buttons10 = Button(border, borderwidth=0, bg="white")
    buttons10.place(x=425, y=2, width=46, height=46)
    buttons11 = Button(border, borderwidth=0, bg="white")
    buttons11.place(x=2, y=49, width=46, height=46)
    buttons12 = Button(border, borderwidth=0, bg="white")
    buttons12.place(x=49, y=49, width=46, height=46)
    buttons13 = Button(border, borderwidth=0, bg="white")
    buttons13.place(x=96, y=49, width=46, height=46)
    buttons14 = Button(border, borderwidth=0, bg="white")
    buttons14.place(x=143, y=49, width=46, height=46)
    buttons15 = Button(border, borderwidth=0, bg="white")
    buttons15.place(x=190, y=49, width=46, height=46)
    buttons16 = Button(border, borderwidth=0, bg="white")
    buttons16.place(x=237, y=49, width=46, height=46)
    buttons17 = Button(border, borderwidth=0, bg="white")
    buttons17.place(x=284, y=49, width=46, height=46)
    buttons18 = Button(border, borderwidth=0, bg="white")
    buttons18.place(x=331, y=49, width=46, height=46)
    buttons19 = Button(border, borderwidth=0, bg="white")
    buttons19.place(x=378, y=49, width=46, height=46)
    buttons20 = Button(border, borderwidth=0, bg="white")
    buttons20.place(x=425, y=49, width=46, height=46)
    buttons21 = Button(border, borderwidth=0, bg="white")
    buttons21.place(x=2, y=96, width=46, height=46)
    buttons22 = Button(border, borderwidth=0, bg="white")
    buttons22.place(x=49, y=96, width=46, height=46)
    buttons23 = Button(border, borderwidth=0, bg="white")
    buttons23.place(x=96, y=96, width=46, height=46)
    buttons24 = Button(border, borderwidth=0, bg="white")
    buttons24.place(x=143, y=96, width=46, height=46)
    buttons25 = Button(border, borderwidth=0, bg="white")
    buttons25.place(x=190, y=96, width=46, height=46)
    buttons26 = Button(border, borderwidth=0, bg="white")
    buttons26.place(x=237, y=96, width=46, height=46)
    buttons27 = Button(border, borderwidth=0, bg="white")
    buttons27.place(x=284, y=96, width=46, height=46)
    buttons28 = Button(border, borderwidth=0, bg="white")
    buttons28.place(x=331, y=96, width=46, height=46)
    buttons29 = Button(border, borderwidth=0, bg="white")
    buttons29.place(x=378, y=96, width=46, height=46)
    buttons30 = Button(border, borderwidth=0, bg="white")
    buttons30.place(x=425, y=96, width=46, height=46)
    buttons31 = Button(border, borderwidth=0, bg="white")
    buttons31.place(x=2, y=143, width=46, height=46)
    buttons32 = Button(border, borderwidth=0, bg="white")
    buttons32.place(x=49, y=143, width=46, height=46)
    buttons33 = Button(border, borderwidth=0, bg="white")
    buttons33.place(x=96, y=143, width=46, height=46)
    buttons34 = Button(border, borderwidth=0, bg="white")
    buttons34.place(x=143, y=143, width=46, height=46)
    buttons35 = Button(border, borderwidth=0, bg="white")
    buttons35.place(x=190, y=143, width=46, height=46)
    buttons36 = Button(border, borderwidth=0, bg="white")
    buttons36.place(x=237, y=143, width=46, height=46)
    buttons37 = Button(border, borderwidth=0, bg="white")
    buttons37.place(x=284, y=143, width=46, height=46)
    buttons38 = Button(border, borderwidth=0, bg="white")
    buttons38.place(x=331, y=143, width=46, height=46)
    buttons39 = Button(border, borderwidth=0, bg="white")
    buttons39.place(x=378, y=143, width=46, height=46)
    buttons40 = Button(border, borderwidth=0, bg="white")
    buttons40.place(x=425, y=143, width=46, height=46)
    buttons41 = Button(border, borderwidth=0, bg="white")
    buttons41.place(x=2, y=190, width=46, height=46)
    buttons42 = Button(border, borderwidth=0, bg="white")
    buttons42.place(x=49, y=190, width=46, height=46)
    buttons43 = Button(border, borderwidth=0, bg="white")
    buttons43.place(x=96, y=190, width=46, height=46)
    buttons44 = Button(border, borderwidth=0, bg="white")
    buttons44.place(x=143, y=190, width=46, height=46)
    buttons45 = Button(border, borderwidth=0, bg="white")
    buttons45.place(x=190, y=190, width=46, height=46)
    buttons46 = Button(border, borderwidth=0, bg="white")
    buttons46.place(x=237, y=190, width=46, height=46)
    buttons47 = Button(border, borderwidth=0, bg="white")
    buttons47.place(x=284, y=190, width=46, height=46)
    buttons48 = Button(border, borderwidth=0, bg="white")
    buttons48.place(x=331, y=190, width=46, height=46)
    buttons49 = Button(border, borderwidth=0, bg="white")
    buttons49.place(x=378, y=190, width=46, height=46)
    buttons50 = Button(border, borderwidth=0, bg="white")
    buttons50.place(x=425, y=190, width=46, height=46)
    buttons51 = Button(border, borderwidth=0, bg="white")
    buttons51.place(x=2, y=237, width=46, height=46)
    buttons52 = Button(border, borderwidth=0, bg="white")
    buttons52.place(x=49, y=237, width=46, height=46)
    buttons53 = Button(border, borderwidth=0, bg="white")
    buttons53.place(x=96, y=237, width=46, height=46)
    buttons54 = Button(border, borderwidth=0, bg="white")
    buttons54.place(x=143, y=237, width=46, height=46)
    buttons55 = Button(border, borderwidth=0, bg="white")
    buttons55.place(x=190, y=237, width=46, height=46)
    buttons56 = Button(border, borderwidth=0, bg="white")
    buttons56.place(x=237, y=237, width=46, height=46)
    buttons57 = Button(border, borderwidth=0, bg="white")
    buttons57.place(x=284, y=237, width=46, height=46)
    buttons58 = Button(border, borderwidth=0, bg="white")
    buttons58.place(x=331, y=237, width=46, height=46)
    buttons59 = Button(border, borderwidth=0, bg="white")
    buttons59.place(x=378, y=237, width=46, height=46)
    buttons60 = Button(border, borderwidth=0, bg="white")
    buttons60.place(x=425, y=237, width=46, height=46)
    buttons61 = Button(border, borderwidth=0, bg="white")
    buttons61.place(x=2, y=284, width=46, height=46)
    buttons62 = Button(border, borderwidth=0, bg="white")
    buttons62.place(x=49, y=284, width=46, height=46)
    buttons63 = Button(border, borderwidth=0, bg="white")
    buttons63.place(x=96, y=284, width=46, height=46)
    buttons64 = Button(border, borderwidth=0, bg="white")
    buttons64.place(x=143, y=284, width=46, height=46)
    buttons65 = Button(border, borderwidth=0, bg="white")
    buttons65.place(x=190, y=284, width=46, height=46)
    buttons66 = Button(border, borderwidth=0, bg="white")
    buttons66.place(x=237, y=284, width=46, height=46)
    buttons67 = Button(border, borderwidth=0, bg="white")
    buttons67.place(x=284, y=284, width=46, height=46)
    buttons68 = Button(border, borderwidth=0, bg="white")
    buttons68.place(x=331, y=284, width=46, height=46)
    buttons69 = Button(border, borderwidth=0, bg="white")
    buttons69.place(x=378, y=284, width=46, height=46)
    buttons70 = Button(border, borderwidth=0, bg="white")
    buttons70.place(x=425, y=284, width=46, height=46)
    buttons71 = Button(border, borderwidth=0, bg="white")
    buttons71.place(x=2, y=331, width=46, height=46)
    buttons72 = Button(border, borderwidth=0, bg="white")
    buttons72.place(x=49, y=331, width=46, height=46)
    buttons73 = Button(border, borderwidth=0, bg="white")
    buttons73.place(x=96, y=331, width=46, height=46)
    buttons74 = Button(border, borderwidth=0, bg="white")
    buttons74.place(x=143, y=331, width=46, height=46)
    buttons75 = Button(border, borderwidth=0, bg="white")
    buttons75.place(x=190, y=331, width=46, height=46)
    buttons76 = Button(border, borderwidth=0, bg="white")
    buttons76.place(x=237, y=331, width=46, height=46)
    buttons77 = Button(border, borderwidth=0, bg="white")
    buttons77.place(x=284, y=331, width=46, height=46)
    buttons78 = Button(border, borderwidth=0, bg="white")
    buttons78.place(x=331, y=331, width=46, height=46)
    buttons79 = Button(border, borderwidth=0, bg="white")
    buttons79.place(x=378, y=331, width=46, height=46)
    buttons80 = Button(border, borderwidth=0, bg="white")
    buttons80.place(x=425, y=331, width=46, height=46)
    buttons81 = Button(border, borderwidth=0, bg="white")
    buttons81.place(x=2, y=378, width=46, height=46)
    buttons82 = Button(border, borderwidth=0, bg="white")
    buttons82.place(x=49, y=378, width=46, height=46)
    buttons83 = Button(border, borderwidth=0, bg="white")
    buttons83.place(x=96, y=378, width=46, height=46)
    buttons84 = Button(border, borderwidth=0, bg="white")
    buttons84.place(x=143, y=378, width=46, height=46)
    buttons85 = Button(border, borderwidth=0, bg="white")
    buttons85.place(x=190, y=378, width=46, height=46)
    buttons86 = Button(border, borderwidth=0, bg="white")
    buttons86.place(x=237, y=378, width=46, height=46)
    buttons87 = Button(border, borderwidth=0, bg="white")
    buttons87.place(x=284, y=378, width=46, height=46)
    buttons88 = Button(border, borderwidth=0, bg="white")
    buttons88.place(x=331, y=378, width=46, height=46)
    buttons89 = Button(border, borderwidth=0, bg="white")
    buttons89.place(x=378, y=378, width=46, height=46)
    buttons90 = Button(border, borderwidth=0, bg="white")
    buttons90.place(x=425, y=378, width=46, height=46)
    buttons91 = Button(border, borderwidth=0, bg="white")
    buttons91.place(x=2, y=425, width=46, height=46)
    buttons92 = Button(border, borderwidth=0, bg="white")
    buttons92.place(x=49, y=425, width=46, height=46)
    buttons93 = Button(border, borderwidth=0, bg="white")
    buttons93.place(x=96, y=425, width=46, height=46)
    buttons94 = Button(border, borderwidth=0, bg="white")
    buttons94.place(x=143, y=425, width=46, height=46)
    buttons95 = Button(border, borderwidth=0, bg="white")
    buttons95.place(x=190, y=425, width=46, height=46)
    buttons96 = Button(border, borderwidth=0, bg="white")
    buttons96.place(x=237, y=425, width=46, height=46)
    buttons97 = Button(border, borderwidth=0, bg="white")
    buttons97.place(x=284, y=425, width=46, height=46)
    buttons98 = Button(border, borderwidth=0, bg="white")
    buttons98.place(x=331, y=425, width=46, height=46)
    buttons99 = Button(border, borderwidth=0, bg="white")
    buttons99.place(x=378, y=425, width=46, height=46)
    buttons100 = Button(border, borderwidth=0, bg="white")
    buttons100.place(x=425, y=425, width=46, height=46)
    
    buttona3 = Button(game3,borderwidth=0, highlightthickness=0,image=questionpicture1)
    buttona3.place(x=10,y=100,width=50,height=50)
    buttona3.config(command=click33)
def click4():
    game4 = Toplevel()
    game4.title("Anagram")
    back = PhotoImage(file="normal.png")
    background=back.subsample(2,2)
    label4 = Label(game4, image=background)
    label4.pack()
    def click44():
        game44=Toplevel()
        game44.title("rules")
        bkkkk=PhotoImage(file="4.1.png")
        bk4 = bkkkk.subsample(2,2)
        label44= Label(game44, image=bk4)
        label44.pack()
        game44.mainloop()
    buttona4 = Button(game4,borderwidth=0, highlightthickness=0,image=questionpicture1)
    buttona4.place(x=10,y=100,width=50,height=50)
    buttona4.config(command=click44)
    list_=[]
    game4.mainloop()
photo = PhotoImage(file="1.png")
one= PhotoImage(file="1).png")
two= PhotoImage(file="2).png")
three= PhotoImage(file="3).png")
four= PhotoImage(file="4).png")
images = photo.subsample(2,2)
imageone = one.subsample(2,2) 
imagetwo = two.subsample(2,2)
imagethree = three.subsample(2,2)
imagefour = four.subsample(2,2) 
label = Label(window, image=images)
button1 = Button(window,text="",borderwidth=0, highlightthickness=0,image=imageone)
button1.place(x=227,y=99,width=202,height=157)
button2 = Button(window,text="",borderwidth=0, highlightthickness=0,image=imagetwo)
button2.place(x=525,y=99,width=202,height=157)
button3 = Button(window,text="",borderwidth=0, highlightthickness=0,image=imagethree)
button3.place(x=227,y=290,width=202,height=157)
button4 = Button(window,text="",borderwidth=0, highlightthickness=0,image=imagefour)
button4.place(x=525,y=290,width=202,height=157)
label.pack()
button1.config(command=choice1)
button2.config(command=click2)
button3.config(command=click3)
button4.config(command=click4)
window.mainloop()