from tkinter import *

window = Tk()
questionpicture=PhotoImage(file="question.png")
questionpicture1=questionpicture.subsample(2,2)
def click1():
    game1 = Toplevel()
    game1.title("21 games")
    back = PhotoImage(file="normal.png")
    background=back.subsample(2,2)
    totalnumber=21
    label1 = Label(game1, image=background,text=f"Total number:{totalnumber}",compound="bottom",font=("Ariel",28),anchor="n")
    label1.pack()
    listplayer=[]
    listcomputer=[]
    Text.insert(END,str(listplayer))
    Text.insert(END,str(listcomputer))
    def click11():
        game11=Toplevel()
        game11.title("rules")
        bk=PhotoImage(file="1.1.png")
        bk1 = bk.subsample(2,2)
        label11= Label(game11, image=bk1)
        label11.pack()
        game11.mainloop()
    def add1():
        nonlocal totalnumber
        totalnumber-=1
        listplayer.append(1)
        Text.insert(END,str(listplayer))
        label1.config(text=f"Total number:{totalnumber}")
        totalnumber-=3
        listcomputer.append(3)
        Text.insert(END,str(listcomputer))
        label1.config(text=f"Total number:{totalnumber}")
    def add2():
        nonlocal totalnumber
        totalnumber-=2
        listplayer.append(2)
        Text.insert(END,str(listplayer))
        label1.config(text=f"Total number:{totalnumber}")
        totalnumber-=2
        listcomputer.append(2)
        Text.insert(END,str(listcomputer))
        label1.config(text=f"Total number:{totalnumber}")
    def add3():
        nonlocal totalnumber
        totalnumber-=3
        listplayer.append(3)
        Text.insert(END,str(listplayer))
        label1.config(text=f"Total number:{totalnumber}")
        totalnumber-=1
        listcomputer.append(1)
        Text.insert(END,str(listcomputer))
        label1.config(text=f"Total number:{totalnumber}")
    buttona1 = Button(game1,borderwidth=0, highlightthickness=0,image=questionpicture1)
    buttona1.place(x=10,y=100,width=50,height=50)
    buttona1.config(command=click11)
    buttonone = Button(game1, text="1",bg="#41AB4C")
    buttonone.place(x=180,y=250,width=150,height=150)
    buttontwo = Button(game1,text="2",bg="#41AB4C")
    buttontwo.place(x=406,y=250,width=150,height=150)
    buttonthree = Button(game1,text="3",bg="#41AB4C")
    buttonthree.place(x=632,y=250,width=150,height=150)
    buttonone.config(command=add1)
    buttontwo.config(command=add2)
    buttonthree.config(command=add3)
    game1.mainloop()
def click2():
    game2 = Toplevel()
    game2.title("Tic Tac Toe")
    back = PhotoImage(file="normal.png")
    background=back.subsample(2,2)
    label2 = Label(game2, image=background)
    label2.pack()
    def click22():
        game22=Toplevel()
        game22.title("rules")
        bkk=PhotoImage(file="2.1.png")
        bk2 = bkk.subsample(2,2)
        label22= Label(game22, image=bk2)
        label22.pack()
        game22.mainloop()
    buttona2 = Button(game2,borderwidth=0, highlightthickness=0,image=questionpicture1)
    buttona2.place(x=10,y=100,width=50,height=50)
    buttona2.config(command=click22)

    game2.mainloop()
def click3():
    game3 = Toplevel()
    game3.title("Find planes' head")
    back = PhotoImage(file="normal.png")
    background=back.subsample(2,2)
    label3 = Label(game3, image=background)
    label3.pack()
    def click33():
        game33=Toplevel()
        game33.title("rules")
        bkkk=PhotoImage(file="3.1.png")
        bk3 = bkkk.subsample(2,2)
        label33= Label(game33, image=bk3)
        label33.pack()
        game33.mainloop()
    buttona3 = Button(game3,borderwidth=0, highlightthickness=0,image=questionpicture1)
    buttona3.place(x=10,y=100,width=50,height=50)
    buttona3.config(command=click33)
    game3.mainloop()
def click4():
    game4 = Toplevel()
    game4.title("Anagram")
    back = PhotoImage(file="normal.png")
    background=back.subsample(2,2)
    label4 = Label(game4, image=background)
    label4.pack()
    def click44():
        game44=Toplevel()
        game44.title("rules")
        bkkkk=PhotoImage(file="4.1.png")
        bk4 = bkkkk.subsample(2,2)
        label44= Label(game44, image=bk4)
        label44.pack()
        game44.mainloop()
    buttona4 = Button(game4,borderwidth=0, highlightthickness=0,image=questionpicture1)
    buttona4.place(x=10,y=100,width=50,height=50)
    buttona4.config(command=click44)
    list_=[]
    game4.mainloop()
photo = PhotoImage(file="1.png")
one= PhotoImage(file="1).png")
two= PhotoImage(file="2).png")
three= PhotoImage(file="3).png")
four= PhotoImage(file="4).png")
images = photo.subsample(2,2)
imageone = one.subsample(2,2) 
imagetwo = two.subsample(2,2)
imagethree = three.subsample(2,2)
imagefour = four.subsample(2,2) 
label = Label(window, image=images)
button1 = Button(window,text="",borderwidth=0, highlightthickness=0,image=imageone)
button1.place(x=227,y=99,width=202,height=157)
button2 = Button(window,text="",borderwidth=0, highlightthickness=0,image=imagetwo)
button2.place(x=525,y=99,width=202,height=157)
button3 = Button(window,text="",borderwidth=0, highlightthickness=0,image=imagethree)
button3.place(x=227,y=290,width=202,height=157)
button4 = Button(window,text="",borderwidth=0, highlightthickness=0,image=imagefour)
button4.place(x=525,y=290,width=202,height=157)
label.pack()
button1.config(command=click1)
button2.config(command=click2)
button3.config(command=click3)
button4.config(command=click4)
window.mainloop()